const BasicURL = "https://instaclone-photos.s3.ap-northeast-2.amazonaws.com/"

export const aws_address = {
    modal:{
        video:`${BasicURL}assets/projectImg/modal/Modal.mov`,
        mac:`${BasicURL}assets/projectImg/modal/onMac.png`,
        one:`${BasicURL}assets/projectImg/modal/MotionHome.png`,
        two:`${BasicURL}assets/projectImg/modal/MotionAddPage.png`,
        three:`${BasicURL}assets/projectImg/modal/MotionPhoto.png`,
        four:`${BasicURL}assets/projectImg/modal/MotionFull.png`,
    },
    kakao:{
        video:`${BasicURL}assets/projectImg/kakao/html.mov`,
        mac:`${BasicURL}assets/projectImg/kakao/onMac.png`,
        one:`${BasicURL}assets/projectImg/kakao/kokoaFirstPage.png`,
        two:`${BasicURL}assets/projectImg/kakao/kokoaJoin.png`,
        three:`${BasicURL}assets/projectImg/kakao/kokoChat.png`,
        four:`${BasicURL}assets/projectImg/kakao/Mypage.png`,
    },
    youtube:{
        video:`${BasicURL}assets/projectImg/youtube/Youtube480.mov`,
        mac:`${BasicURL}assets/projectImg/youtube/onMacYou.png`,
        one:`${BasicURL}assets/projectImg/youtube/YoutubeHome.png`,
        two:`${BasicURL}assets/projectImg/youtube/loginPage.png`,
        three:`${BasicURL}assets/projectImg/youtube/uploadPage.png`,
        four:`${BasicURL}assets/projectImg/youtube/profile.png`,
        five:`${BasicURL}assets/projectImg/youtube/editPage.png`,
    },
    movie:{
        video:`${BasicURL}assets/projectImg/reactMovie/MovieApp 480.mov`,
        mac:`${BasicURL}assets/projectImg/reactMovie/onMacYou.png`,
        one:`${BasicURL}assets/projectImg/reactMovie/index.png`,
        two:`${BasicURL}assets/projectImg/reactMovie/Tv.png`,
        three:`${BasicURL}assets/projectImg/reactMovie/Detail.png`,
        four:`${BasicURL}assets/projectImg/reactMovie/search.png`,
    },
    Mmovie:{
        video:`${BasicURL}assets/projectImg/movieApp/movieAppNew.mov`,
        one:`${BasicURL}assets/projectImg/movieApp/google.png`,
        two:`${BasicURL}assets/projectImg/movieApp/HomePage.png`,
        three:`${BasicURL}assets/projectImg/movieApp/Detail.png`,
        four:`${BasicURL}assets/projectImg/movieApp/Search.png`,
        five:`${BasicURL}assets/projectImg/movieApp/LikePage.png`,
    },
    coffee:{
        video:`${BasicURL}assets/projectImg/CoffeeApp/coffeeApp.mov`,
        one:`${BasicURL}assets/projectImg/CoffeeApp/Index.png`,
        two:`${BasicURL}assets/projectImg/CoffeeApp/Home.png`,
        three:`${BasicURL}assets/projectImg/CoffeeApp/Login.png`,
        four:`${BasicURL}assets/projectImg/CoffeeApp/Create.png`,
        five:`${BasicURL}assets/projectImg/CoffeeApp/Mobile.png`,
    },
    review:{
        video:`${BasicURL}assets/projectImg/reviewApp/review480.mov`,
        one:`${BasicURL}assets/projectImg/reviewApp/Home.png`,
        two:`${BasicURL}assets/projectImg/reviewApp/Login.png`,
        three:`${BasicURL}assets/projectImg/reviewApp/Detail.png`,
        four:`${BasicURL}assets/projectImg/reviewApp/Search.png`,
    }
}

